version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Build React App
          command: npm run build

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Python & EB CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip3 install --upgrade pip
            sudo pip3 install awsebcli --upgrade --user
      - run:
          name: Deploy to AWS Elastic Beanstalk
          command: |
            eb init -p node.js test-app --region us-east-1
            eb deploy 
workflows:
  version: 2
  deploy_react_app:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - build